// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package charlakata

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayer creates a new instance of MockPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayer {
	mock := &MockPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayer is an autogenerated mock type for the Player type
type MockPlayer struct {
	mock.Mock
}

type MockPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayer) EXPECT() *MockPlayer_Expecter {
	return &MockPlayer_Expecter{mock: &_m.Mock}
}

// DealDamage provides a mock function for the type MockPlayer
func (_mock *MockPlayer) DealDamage(target Player, damage int) {
	_mock.Called(target, damage)
	return
}

// MockPlayer_DealDamage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DealDamage'
type MockPlayer_DealDamage_Call struct {
	*mock.Call
}

// DealDamage is a helper method to define mock.On call
//   - target Player
//   - damage int
func (_e *MockPlayer_Expecter) DealDamage(target interface{}, damage interface{}) *MockPlayer_DealDamage_Call {
	return &MockPlayer_DealDamage_Call{Call: _e.mock.On("DealDamage", target, damage)}
}

func (_c *MockPlayer_DealDamage_Call) Run(run func(target Player, damage int)) *MockPlayer_DealDamage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Player
		if args[0] != nil {
			arg0 = args[0].(Player)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayer_DealDamage_Call) Return() *MockPlayer_DealDamage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_DealDamage_Call) RunAndReturn(run func(target Player, damage int)) *MockPlayer_DealDamage_Call {
	_c.Run(run)
	return _c
}

// GetHealth provides a mock function for the type MockPlayer
func (_mock *MockPlayer) GetHealth() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPlayer_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type MockPlayer_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) GetHealth() *MockPlayer_GetHealth_Call {
	return &MockPlayer_GetHealth_Call{Call: _e.mock.On("GetHealth")}
}

func (_c *MockPlayer_GetHealth_Call) Run(run func()) *MockPlayer_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_GetHealth_Call) Return(n int) *MockPlayer_GetHealth_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPlayer_GetHealth_Call) RunAndReturn(run func() int) *MockPlayer_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetLevel provides a mock function for the type MockPlayer
func (_mock *MockPlayer) GetLevel() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLevel")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPlayer_GetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLevel'
type MockPlayer_GetLevel_Call struct {
	*mock.Call
}

// GetLevel is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) GetLevel() *MockPlayer_GetLevel_Call {
	return &MockPlayer_GetLevel_Call{Call: _e.mock.On("GetLevel")}
}

func (_c *MockPlayer_GetLevel_Call) Run(run func()) *MockPlayer_GetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_GetLevel_Call) Return(n int) *MockPlayer_GetLevel_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPlayer_GetLevel_Call) RunAndReturn(run func() int) *MockPlayer_GetLevel_Call {
	_c.Call.Return(run)
	return _c
}

// IsAlive provides a mock function for the type MockPlayer
func (_mock *MockPlayer) IsAlive() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAlive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPlayer_IsAlive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAlive'
type MockPlayer_IsAlive_Call struct {
	*mock.Call
}

// IsAlive is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) IsAlive() *MockPlayer_IsAlive_Call {
	return &MockPlayer_IsAlive_Call{Call: _e.mock.On("IsAlive")}
}

func (_c *MockPlayer_IsAlive_Call) Run(run func()) *MockPlayer_IsAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_IsAlive_Call) Return(b bool) *MockPlayer_IsAlive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPlayer_IsAlive_Call) RunAndReturn(run func() bool) *MockPlayer_IsAlive_Call {
	_c.Call.Return(run)
	return _c
}

// TakeDamage provides a mock function for the type MockPlayer
func (_mock *MockPlayer) TakeDamage(damage int) {
	_mock.Called(damage)
	return
}

// MockPlayer_TakeDamage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TakeDamage'
type MockPlayer_TakeDamage_Call struct {
	*mock.Call
}

// TakeDamage is a helper method to define mock.On call
//   - damage int
func (_e *MockPlayer_Expecter) TakeDamage(damage interface{}) *MockPlayer_TakeDamage_Call {
	return &MockPlayer_TakeDamage_Call{Call: _e.mock.On("TakeDamage", damage)}
}

func (_c *MockPlayer_TakeDamage_Call) Run(run func(damage int)) *MockPlayer_TakeDamage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayer_TakeDamage_Call) Return() *MockPlayer_TakeDamage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_TakeDamage_Call) RunAndReturn(run func(damage int)) *MockPlayer_TakeDamage_Call {
	_c.Run(run)
	return _c
}
